name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Explicitly delete the Gradle cache to ensure a fresh build
      - name: Delete Gradle Cache
        run: rm -rf ~/.gradle/caches/

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # Remove the 'cache: gradle' option to prevent caching issues
          # cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # Add --rerun-tasks to force all tasks to be executed from scratch
        run: ./gradlew build --rerun-tasks
